version: '3'
services:
  front:
    container_name: front
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front/src:/app/src
      - ./front/public:/app/public
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - back
    networks:
      - loteria

  back:
    container_name: back
    build:
      context: ./back
      dockerfile: .docker/Dockerfile
    image: 'laravelapp'
    ports:
      - 8080:80
    volumes:
      - ./back:/app
    restart: always
    depends_on:
      - banco
    networks:
      - loteria

  banco:
      image: mysql:5.7
      container_name: banco
      ports:
        - '3306:3306'
      volumes:
        - ./banco:/var/lib/mysql
      environment:
        - MYSQL_DATABASE=loteria
        - MYSQL_ROOT_PASSWORD=loteria
        - MYSQL_USER=loteria
        - MYSQL_PASSWORD=loteria
      networks:
        - loteria

networks:
  loteria:
    driver: bridge